version: '3'
services:
  rill-flow:
    image: weibocom/rill-flow
    depends_on:
      - cache
      - jaeger
    links:
      - rill-flow-mysql
    ports:
      - "8080:8080"
    environment:
      - RILL_FLOW_DESCRIPTOR_REDIS_HOST=cache
      - RILL_FLOW_DEFAULT_REDIS_HOST=cache
      - RILL_FLOW_TRACE_ENDPOINT=http://jaeger:4317
      - RILL_FLOW_CALLBACK_URL=http://rill-flow:8080/flow/finish.json
      - RILL_FLOW_TRACE_QUERY_HOST=http://jaeger:16686
  cache:
    image: redis:6.2-alpine
    restart: always
    command: redis-server --save 20 1 --loglevel warning
  jaeger:
    image: jaegertracing/all-in-one:1.39
    restart: always
    ports:
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
  ui:
    image: weibocom/rill-flow-ui
    ports:
      - "80:80"
    depends_on:
      - rill-flow
      - jaeger
    environment:
      - BACKEND_SERVER=http://rill-flow:8080
  sample-executor:
    image: weibocom/rill-flow-sample:sample-executor
  rill-flow-mysql:
    image: mysql:5.7
    stdin_open: true
    tty: true
    container_name: rill-flow-mysql
    restart: always
    command:  --bind-address=0.0.0.0 --default-authentication-plugin=mysql_native_password
    volumes:
        - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=rill_flow
      - MYSQL_ROOT_HOST=%